apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: plugin-serving-cert
  name: troubleshooting-panel-console-plugin
  namespace: korrel8r
  labels:
    app: troubleshooting-panel-console-plugin
    app.kubernetes.io/component: troubleshooting-panel-console-plugin
    app.kubernetes.io/instance: troubleshooting-panel-console-plugin
    app.kubernetes.io/part-of: troubleshooting-panel-console-plugin
spec:
  ports:
    - name: 9443-tcp
      protocol: TCP
      port: 9443
      targetPort: 9443
  selector:
    app: troubleshooting-panel-console-plugin
  type: ClusterIP
  sessionAffinity: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: troubleshooting-panel-console-plugin
  namespace: korrel8r
  labels:
    app: troubleshooting-panel-console-plugin
    app.kubernetes.io/component: troubleshooting-panel-console-plugin
    app.kubernetes.io/instance: troubleshooting-panel-console-plugin
    app.kubernetes.io/part-of: troubleshooting-panel-console-plugin
    app.openshift.io/runtime-namespace: korrel8r
spec:
  replicas: 1
  selector:
    matchLabels:
      app: troubleshooting-panel-console-plugin
  template:
    metadata:
      labels:
        app: troubleshooting-panel-console-plugin
    spec:
      containers:
        - name: troubleshooting-panel-console-plugin
          image: "quay.io/repo-name/troubleshooting-panel-console-plugin:latest"
          args:
            - "-port=9443"
            - "-cert=/var/serving-cert/tls.crt"
            - "-key=/var/serving-cert/tls.key"
            - "-plugin-config-path=/etc/plugin/config.yaml"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 9443
              protocol: TCP
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: plugin-serving-cert
              readOnly: true
              mountPath: /var/serving-cert
      volumes:
        - name: plugin-serving-cert
          secret:
            secretName: plugin-serving-cert
            defaultMode: 420
        - name: plugin-conf
          configMap:
            name: troubleshooting-panel-console-plugin-config
            defaultMode: 420
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%

---
apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: troubleshooting-panel-console-plugin
spec:
  displayName: "Troubleshooting Panel view plugin"
  backend:
    type: Service
    service:
      name: troubleshooting-panel-console-plugin
      namespace: korrel8r
      basePath: "/"
      port: 8443
  proxy:
  - alias: korrel8r
    endpoint:
      type: Service
      service:
        name: korrel8r
        namespace: korrel8r
        port: 443


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: troubleshooting-panel-console-plugin-config
  namespace: korrel8r
  labels:
    app: troubleshooting-panel-console-plugin
    app.kubernetes.io/part-of: troubleshooting-panel-console-plugin
data:
  config.yaml: |-
    logsLimit: 100
    timeout: "30s"
